### ISSUE TITLE
Replace lorem ipsum text

### ISSUE THREAD

**Issue by castrojo** [cncf/presentations-website#11]
![image](https://github.com/cncf/presentations-website/assets/1264109/c67bdea5-45a7-48c4-9437-505d33af5fa5)

I'd like to update this text, but this doesn't appear to be where I can do that: https://github.com/cncf/presentations-website/blob/0b2e50bd7da08d9cc98c4f449cfccd3208f21099/web/wp-content/themes/cncf-twenty-two/patterns/pjr-intro.php#L31

**Comment by castrojo** [comment]
Here's the text from Katie that we want on there:

```
CNCF presentations serves as an invaluable resource for the sharing of information, ideas, and messages around cloud-native applications and projects. This community-driven platform serves as a centralized hub for accessing thought-provoking presentations delivered within the ecosystem by industry thought leaders.
```

**Comment by cjyabraham** [comment]
Thanks. I've updated it in WordPress: https://presentations.cncf.io/
