### ISSUE TITLE
Soft launch

### ISSUE THREAD

**Issue by cjyabraham** [cncf/presentations-website#8]
@castrojo LMK when you're ready for this site to go on its production url.

**Comment by castrojo** [comment]
I'd like to get one round in from feedback from the ambassadors (we meet in 2 weeks) to get them contributing so we can get comfortable with the workflow and get more presentations in. 

What does launching entail -- would it be linked from everywhere or could we soft launch it and then build up the presentations before making it more obviously public? Thanks!

**Comment by cjyabraham** [comment]
Yes, we could soft-launch it by just getting it on the production url: presentations.cncf.io. Once we get initial data up on it we could do a proper PR launch and link it in to the other sites etc.

**Comment by castrojo** [comment]
Soft launch works for me, but we still need a validation check, looping in @jeefy 

https://github.com/cncf/presentations/issues/148

**Comment by cjyabraham** [comment]
Soft launch complete: https://presentations.cncf.io/
